version: '3.8'

services:
  migrate:
    image: migrate/migrate
    networks:
      - db
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:root@postgres:5432/farm?sslmode=disable", "up" ]
    depends_on:
      - postgres-db

  # Postgres
  postgres-db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: farm
    volumes:
      - db:/databasedatadb/postgres
    ports:
      - "5332:5332"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  farmish-service:
    container_name: farmish-service
    build: .
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    networks:
      - db

# Docker Networks
networks:
  db:
    driver: bridge

# Docker Volumes
volumes:
  # mongodata:
  db: